project:
  type: website
  
website:
  page-navigation: true
  title: "Environmental Computing" 
  site-url: https://environmentalcomputingsp.netlify.app
  
  repo-url: https://github.com/PaulESantos/environmentalcomputingsp
  repo-actions: [edit, issue]
  favicon: images/favicon.png
  page-footer: 
    right: "Environmental Computing - Spanish | Made with [Quarto](https://quarto.org/)."
    
  sidebar:
    logo: images/E_C_01-01.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://environmentalcomputing.net/
        text: "Environmental Computing"
      - icon: github
        href: https://github.com/PaulESantos/environmentalcomputingsp
        text: "GitHub Repository"
  
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: "index.qmd"
        text: Bienvenido
      - href: "about.qmd"
        text: Sobre el sitio web
      - section: getting-started-with-r/index.qmd
        contents:  
          - getting-started-with-r/data-entry/index.qmd         
          - getting-started-with-r/data-types-structure/index.qmd
          - getting-started-with-r/importing-data/index.qmd      
          - getting-started-with-r/installing-r-rstudio/index.qmd
          - getting-started-with-r/project-management/index.qmd  
          - getting-started-with-r/rstudio-notebooks/index.qmd
      - section: coding-skills/index.qmd 
        contents:
          - coding-skills/asking-code-questions/index.qmd
          - coding-skills/good-practice/index.qmd        
          - coding-skills/loops/index.qmd                
          - coding-skills/version-control/index.qmd
          - coding-skills/writing-functions/index.qmd    
      - section: data-manipulation/index.qmd
        contents:
          - data-manipulation/combining-datasets/index.qmd
          - data-manipulation/making-new-variables/index.qmd
          - data-manipulation/reshaping-data/index.qmd      
          - data-manipulation/subsetting-data/index.qmd
          - data-manipulation/summarising-data/index.qmd
      - section: graphics/index.qmd
        contents: 
          - graphics/basic-plotting/one-continuous/index.qmd  
          - graphics/basic-plotting/two-continuous/index.qmd 
          - graphics/basic-plotting/one-continuous-one-factor/index.qmd
          - graphics/ggplot/ggplot-basics/index.qmd  
          - graphics/ggplot/ggplot-appearance/index.qmd  
          - graphics/ggplot/ggplot-labels/index.qmd 
          - graphics/ggplot/ggplot-colour-shapes/index.qmd
          - graphics/ggplot/ggplot-barplot/index.qmd                 
          - graphics/multivariate-vis/mds/index.qmd
          - graphics/multivariate-vis/pca/index.qmd
          - graphics/multivariate-vis/cluster-analysis/index.qmd
          - graphics/multivariate-vis/heatmaps/index.qmd        
          - graphics/spatial-vis/basic-raster/index.qmd
          - graphics/spatial-vis/simple-maps/index.qmd
          - graphics/spatial-vis/interactive/index.qmd
      - section: statistics/index.qmd
        contents:
          - statistics/t-tests/one-sample-t-test/index.qmd                       
          - statistics/t-tests/paired-t-test/index.qmd                            
          - statistics/t-tests/two-sample-t-test/index.qmd 
          
          - statistics/linear-models/linear-regression/index.qmd
          - statistics/linear-models/linear-regression/interpret-lm-coeffs/index.qmd
          
          - statistics/linear-models/anova/anova-single/index.qmd
          - statistics/linear-models/anova/anova-factorial/index.qmd
          - statistics/linear-models/anova/anova-nested/index.qmd                
          - statistics/linear-models/interactions/index.qmd      
          
          - statistics/glms/glm-1/index.qmd
          - statistics/glms/glm-2/index.qmd                                         
          - statistics/glms/interpret-glm-coeffs/index.qmd
          
          - statistics/mixed-models/mixed-model-1/index.qmd                       
          - statistics/mixed-models/mixed-model-2/index.qmd                       
          - statistics/mixed-models/mixed-model-3/index.qmd 
          
          - statistics/gams/index.qmd 
          
          - statistics/categorical/goodness-of-fit/index.qmd
          - statistics/categorical/contingency-tables/index.qmd
          - statistics/categorical/fishers-exact/index.qmd  
          
          - statistics/power-analysis/index.qmd 
          
          - statistics/mvabund/index.qmd 
          
          - statistics/time-series/index.qmd

          - statistics/meta-analysis/meta-analysis-1/index.qmd
          - statistics/meta-analysis/meta-analysis-2/index.qmd                    
          - statistics/meta-analysis/meta-analysis-3/index.qmd                    

      - section: datasets/index.qmd 
        contents:
          - datasets/index.qmd

format:
  html:
    grid:
      sidebar-width: 400px
      body-width: 700px
    theme:
      light: [cosmo, theme-ligth.scss]
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true 
    
filters:
  - include-files.lua
  - quarto    
