---
title: ""
output: html_document
---


# Bienvenido

Bienvenidos al sitio web de la versión en español de [Environmental Computing](https://environmentalcomputing.net/). Aquí se presenta información detallada sobre cómo emplear el lenguaje de programación R para la gestión y análisis de datos ambientales. Aprenderás sobre manipulación, análisis y visualización de datos, desarrollando habilidades clave para asegurar la reproducibilidad en los procesos de gestión de datos. Este sitio es un recurso esencial para aquellos en el campo de las ciencias biológicas y ambientales que buscan utilizar R en su trabajo.

## Sobre la Traducción

La versión en español de [Environmental Computing](https://environmentalcomputing.net/) es un proyecto desarrollado con el fin de proporcionar a los profesionales de las ciencias biológicas una herramienta de consulta accesible para el uso de R. La traducción fue realizada por [Paul Efren Santos Andrade](https://paulefrensa.netlify.app/). Extendemos nuestro agradecimiento al profesor [Will Cornwell](http://willcornwell.org/) por su generosidad al compartir la información y otorgarnos la autorización para difundir la traducción del contenido original de [Environmental Computing](https://environmentalcomputing.net/).


