<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Environmental Computing - Fixed-effect and Random-effect Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../statistics/meta-analysis/meta-analysis-3/index.html" rel="next">
<link href="../../../statistics/meta-analysis/meta-analysis-1/index.html" rel="prev">
<link href="../../../images/favicon.png" rel="icon" type="image/png">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-sidebar docked">


<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../statistics/index.html">Statistics</a></li><li class="breadcrumb-item"><a href="../../../statistics/meta-analysis/meta-analysis-2/index.html">Fixed-effect and Random-effect Models</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../../../index.html" class="sidebar-logo-link">
      <img src="../../../images/E_C_01-01.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://environmentalcomputing.net/" title="Environmental Computing" class="quarto-navigation-tool px-1" aria-label="Environmental Computing"><i class="bi bi-globe"></i></a>
    <a href="https://github.com/PaulESantos/environmentalcomputingsp" title="GitHub Repository" class="quarto-navigation-tool px-1" aria-label="GitHub Repository"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bienvenido</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../about.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sobre el sitio web</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../getting-started-with-r/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la programación con R</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../getting-started-with-r/data-entry/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Estructura de una base de datos - Data Entry</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../getting-started-with-r/data-types-structure/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tipos de datos + Estructura</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../getting-started-with-r/importing-data/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Importing Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../getting-started-with-r/installing-r-rstudio/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Instalando R y RStudio</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../getting-started-with-r/project-management/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gestión de proyectos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../getting-started-with-r/rstudio-notebooks/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Utilizando R Notebooks</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../coding-skills/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción a la programación</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../coding-skills/asking-code-questions/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preguntas sobre código</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../coding-skills/good-practice/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Buenas prácticas de codificación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../coding-skills/loops/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Usando bucles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../coding-skills/version-control/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Control de versiones</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../coding-skills/writing-functions/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Como escribir funciones</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../data-manipulation/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Manipulación de Datos</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../data-manipulation/combining-datasets/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Combinando conjuntos de datos.</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../data-manipulation/making-new-variables/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Creación de nuevas variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../data-manipulation/reshaping-data/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reorganización de datos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../data-manipulation/subsetting-data/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Subconjuntos de datos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../data-manipulation/summarising-data/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resumiendo datos</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../graphics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gráficos</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/basic-plotting/one-continuous/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Una Variable Continua</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/basic-plotting/two-continuous/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dos Variables Continuas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/basic-plotting/one-continuous-one-factor/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Una Variable Continua y una Variable Categórica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/ggplot/ggplot-basics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fundamentos de ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/ggplot/ggplot-appearance/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Personalización de un gráfico en ggplot</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/ggplot/ggplot-labels/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Títulos y etiquetas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/ggplot/ggplot-colour-shapes/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Colores y formas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/ggplot/ggplot-barplot/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Gráfico de barras con barras de error</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/multivariate-vis/mds/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Escalamiento multidimensional</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/multivariate-vis/pca/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis de Componentes Principales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/multivariate-vis/cluster-analysis/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis de Clúster</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/multivariate-vis/heatmaps/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Heatmaps - Mapa de Calor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/spatial-vis/basic-raster/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Fundamentos de imagenes raster</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/spatial-vis/simple-maps/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mapas simples con ggmap</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../graphics/spatial-vis/interactive/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Mapas interactivos en R</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../statistics/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistics</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/t-tests/one-sample-t-test/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prueba de una muestra con t de Student</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/t-tests/paired-t-test/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">T-test emparejado</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/t-tests/two-sample-t-test/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Two Sample T-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/linear-models/linear-regression/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Regresión Lineal</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/linear-models/linear-regression/interpret-lm-coeffs/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interpretación de Regresiones Lineales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/linear-models/anova/anova-single/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA de un solo factor</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/linear-models/anova/anova-factorial/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA Factorial</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/linear-models/anova/anova-nested/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ANOVA anidado</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/linear-models/interactions/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Comprendiendo las interacciones</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/glms/glm-1/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción y Datos Binarios</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/glms/glm-2/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datos de recuento</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/glms/interpret-glm-coeffs/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interpretación de los GLMs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/mixed-models/mixed-model-1/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/mixed-models/mixed-model-2/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Factores Cruzados y Anidados</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/mixed-models/mixed-model-3/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modelos mixtos generalizados</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/gams/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modelos Aditivos Generalizados (GAM)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/categorical/goodness-of-fit/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prueba de bondad de ajuste</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/categorical/contingency-tables/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tablas de contingencia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/categorical/fishers-exact/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prueba Exacta de Fisher</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/power-analysis/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis de poder</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/mvabund/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis multivariado con <code>mvabund</code></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/time-series/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Predicción de series temporales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/meta-analysis/meta-analysis-1/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction al meta-análisis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/meta-analysis/meta-analysis-2/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Fixed-effect and Random-effect Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../statistics/meta-analysis/meta-analysis-3/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multilevel Models</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../datasets/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datasets</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../datasets/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Datasets</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#modelos-de-efecto-fijo-y-efecto-aleatorio" id="toc-modelos-de-efecto-fijo-y-efecto-aleatorio" class="nav-link active" data-scroll-target="#modelos-de-efecto-fijo-y-efecto-aleatorio">Modelos de efecto fijo y efecto aleatorio</a></li>
  <li><a href="#ejecutando-un-modelo-de-efecto-común" id="toc-ejecutando-un-modelo-de-efecto-común" class="nav-link" data-scroll-target="#ejecutando-un-modelo-de-efecto-común">Ejecutando un modelo de efecto común</a></li>
  <li><a href="#ejecutando-un-modelo-de-efectos-aleatorios" id="toc-ejecutando-un-modelo-de-efectos-aleatorios" class="nav-link" data-scroll-target="#ejecutando-un-modelo-de-efectos-aleatorios">Ejecutando un modelo de efectos aleatorios</a></li>
  <li><a href="#comprensión-de-la-heterogeneidad" id="toc-comprensión-de-la-heterogeneidad" class="nav-link" data-scroll-target="#comprensión-de-la-heterogeneidad">Comprensión de la heterogeneidad</a></li>
  <li><a href="#meta-regresión-el-modelo-de-efectos-aleatorios" id="toc-meta-regresión-el-modelo-de-efectos-aleatorios" class="nav-link" data-scroll-target="#meta-regresión-el-modelo-de-efectos-aleatorios">Meta-regresión (el modelo de efectos aleatorios)</a></li>
  <li><a href="#comprobando-el-sesgo-de-publicación" id="toc-comprobando-el-sesgo-de-publicación" class="nav-link" data-scroll-target="#comprobando-el-sesgo-de-publicación">Comprobando el sesgo de publicación</a></li>
  <li><a href="#otro-modelo-que-no-conocía-pero-importante" id="toc-otro-modelo-que-no-conocía-pero-importante" class="nav-link" data-scroll-target="#otro-modelo-que-no-conocía-pero-importante">Otro modelo (que no conocía), ¡pero importante!</a></li>
  <li><a href="#más-ayuda-referencias" id="toc-más-ayuda-referencias" class="nav-link" data-scroll-target="#más-ayuda-referencias">Más ayuda (referencias)</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/PaulESantos/environmentalcomputingsp/edit/main/statistics/meta-analysis/meta-analysis-2/index.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/PaulESantos/environmentalcomputingsp/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fixed-effect and Random-effect Models</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Primero lee nuestra <a href="../../../statistics/meta-analysis/meta-analysis-1">introducción al metaanálisis</a> con instrucciones para calcular tamaños del efecto. Ahora, consideramos los modelos estadísticos para estimar los tamaños del efecto medio y la influencia de las variables moderadoras.</p>
<section id="modelos-de-efecto-fijo-y-efecto-aleatorio" class="level3">
<h3 class="anchored" data-anchor-id="modelos-de-efecto-fijo-y-efecto-aleatorio">Modelos de efecto fijo y efecto aleatorio</h3>
<p>Existen dos modelos principales de metaanálisis: 1) el modelo de efecto fijo y 2) el modelo de efecto aleatorio (en realidad, se menciona un tercer tipo, pero este es una extensión del segundo modelo). Debido a que los efectos fijos tienen un significado diferente en otro contexto, esta denominación puede resultar confusa. Por lo tanto, ahora las personas llaman al primer modelo ‘modelo de efecto común’. Puedes ver una representación visual de estos dos modelos (de la Figura 4 en Nakagawa <em>et al.</em> 2017).</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Fixed.png" class="img-fluid" width="225"></p>
</div>
<div class="cell-output-display">
<p><img src="Random.png" class="img-fluid" width="212"></p>
</div>
</div>
<p>Una representación matemática del modelo de efecto común es:</p>
<p><span class="math display">\[\begin{equation}
y_i=b_0+e_i,
\\
e_i\sim \mathcal{N}(0,v_i),\
\end{equation}\]</span>\end{equation}</p>
<p>donde <span class="math inline">\(y_i\)</span> es el tamaño del efecto <span class="math inline">\(i\)</span> (del <span class="math inline">\(i\)</span>-ésimo estudio), <span class="math inline">\(b_0\)</span> es la media general (o media metaanalítica), <span class="math inline">\(e_i\)</span> es una desviación de la media general y sigue una distribución normal con varianza específica del estudio <span class="math inline">\(v_i\)</span> (que se puede obtener a partir de las fórmulas anteriores). Ten en cuenta que los pesos para este modelo son <span class="math inline">\(1/v_i\)</span>. Como puedes ver, este es un modelo muy simple; básicamente, estamos estimando la media considerando los pesos.</p>
<p>Es importante destacar que este modelo asume que existe una media común para todos los estudios incluidos. ¿Es realista esto? Probablemente no, especialmente si estás combinando diferentes especies.</p>
<p>El modelo de efecto aleatorio se puede escribir de la siguiente manera:</p>
<p><span class="math display">\[\begin{equation}
y_i=b_0+s_i+e_i,
\\
s_i\sim \mathcal{N}(0,\tau^2),\
\\
e_i\sim \mathcal{N}(0,v_i),\
\end{equation}\]</span>e_i(0,v_i),<br>
\end{equation}</p>
<p>donde <span class="math inline">\(s_i\)</span> es una desviación específica del estudio de la media general para el <span class="math inline">\(i\)</span>-ésimo estudio, sigue una distribución normal con la varianza entre estudios, a menudo referida como <span class="math inline">\(\tau^2\)</span>, y los demás términos son iguales a los mencionados anteriormente. A diferencia del modelo de efecto común, un modelo de efecto aleatorio asume que diferentes estudios tienen diferentes medias. Ten en cuenta que los pesos para este modelo son <span class="math inline">\(1/(\tau^2+v_i)\)</span>. Volveremos a este punto, ya que resulta ser bastante importante.</p>
</section>
<section id="ejecutando-un-modelo-de-efecto-común" class="level3">
<h3 class="anchored" data-anchor-id="ejecutando-un-modelo-de-efecto-común">Ejecutando un modelo de efecto común</h3>
<p>Utilizaremos la función <code>rma</code> de <code>metafor</code> para ejecutar un modelo de efecto común.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>common_m <span class="ot">&lt;-</span> <span class="fu">rma</span>(<span class="at">yi =</span> yi, <span class="at">vi =</span> vi, <span class="at">method =</span> <span class="st">"FE"</span>, <span class="at">data =</span> dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Especificamos el tamaño del efecto (yi), su varianza (vi), el método (“FE” para efecto fijo) y el marco de datos (dat).</p>
<p>Para ver los resultados, usa <code>summary</code> en el objeto del modelo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(common_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Fixed-Effects Model (k = 102)

   logLik   deviance        AIC        BIC       AICc   
-245.9580   769.0185   493.9160   496.5410   493.9560   

I^2 (total heterogeneity / total variability):   86.87%
H^2 (total variability / sampling variability):  7.61

Test for Heterogeneity:
Q(df = 101) = 769.0185, p-val &lt; .0001

Model Results:

estimate      se     zval    pval   ci.lb   ci.ub      
  0.2088  0.0054  38.3374  &lt;.0001  0.1982  0.2195  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>¡Listo, fue fácil! La media general es estadísticamente significativa y está alrededor de 0.2. ¿Qué significa 0.2? Convertámoslo de vuelta a la escala original: una proporción de respuesta entre las medias del grupo de control y experimental.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fl">0.2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.221403</code></pre>
</div>
</div>
<p>Esto significa que un rasgo de planta (por ejemplo, la masa) fue un 22% más grande en el grupo experimental (RR<span class="math inline">\(=\bar{x}_{E}/\bar{x}_{C}\)</span>), lo cual parece ser un efecto bastante grande (recuerda que necesitamos interpretar nuestros resultados de manera biológicamente significativa). Ten en cuenta que <a href="https://es.wikipedia.org/wiki/Desigualdad_de_Jensen">la desigualdad de Jensen</a> establece que esto está un poco mal, pero no entraremos en eso hoy.</p>
</section>
<section id="ejecutando-un-modelo-de-efectos-aleatorios" class="level3">
<h3 class="anchored" data-anchor-id="ejecutando-un-modelo-de-efectos-aleatorios">Ejecutando un modelo de efectos aleatorios</h3>
<p>Ahora pasamos al modelo de efectos aleatorios, que es un modelo más realista. Nuevamente, utilizamos la función <code>rma</code>, pero esta vez cambiamos el método a REML, que es el método predeterminado y el mejor método para el metanálisis de efectos aleatorios.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>random_m <span class="ot">&lt;-</span> <span class="fu">rma</span>(<span class="at">yi =</span> yi, <span class="at">vi =</span> vi, <span class="at">method =</span> <span class="st">"REML"</span>, <span class="at">data =</span> dat)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(random_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 102; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
  7.0449  -14.0898  -10.0898   -4.8596   -9.9674   

tau^2 (estimated amount of total heterogeneity): 0.0262 (SE = 0.0053)
tau (square root of estimated tau^2 value):      0.1619
I^2 (total heterogeneity / total variability):   88.90%
H^2 (total variability / sampling variability):  9.01

Test for Heterogeneity:
Q(df = 101) = 769.0185, p-val &lt; .0001

Model Results:

estimate      se     zval    pval   ci.lb   ci.ub      
  0.2553  0.0198  12.8899  &lt;.0001  0.2165  0.2941  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Compare la media general de este modelo con el modelo de efecto común. Oh, la media general del modelo de efectos aleatorios es realmente mayor que la del modelo de efectos fijos. Vale, eso a veces sucede (descubriremos que esto probablemente sea una sobreestimación más tarde). Esperamos que el intervalo de confianza del 95% sea más amplio (es decir, más realista) en este modelo de efectos aleatorios, ya que este modelo tiene una mejor suposición que el modelo de efecto común.</p>
</section>
<section id="comprensión-de-la-heterogeneidad" class="level3">
<h3 class="anchored" data-anchor-id="comprensión-de-la-heterogeneidad">Comprensión de la heterogeneidad</h3>
<p>La salida del modelo de efectos aleatorios tiene más elementos que el modelo de efecto común. Tenemos <code>tau^2</code> (<span class="math inline">\(\tau^2\)</span>) y <code>I^2</code> (<span class="math inline">\(I^2\)</span>), dos medidas muy comunes de heterogeneidad (nota que <code>H^2</code>, o <span class="math inline">\(H^2\)</span>, es una transformación de <span class="math inline">\(I^2\)</span>).</p>
<blockquote class="blockquote">
<p>La heterogeneidad es la variación en los tamaños del efecto que no se explica por la varianza del error de muestreo.</p>
</blockquote>
<p>En otras palabras, es la variación real en los datos. Creo que <span class="math inline">\(I^2\)</span> es un índice bastante importante, ya que puede indicar el porcentaje de variación real en tus datos metaanalíticos. Se puede calcular de la siguiente manera (como viste en la figura del modelo de efectos aleatorios anterior):</p>
<p><span class="math display">\[\begin{equation}
I^2=\frac{\tau^2}{(\tau^2+\bar{v})},
\end{equation}\]</span></p>
<p>donde <span class="math inline">\(\bar{v}\)</span> es un valor representativo de <span class="math inline">\(v_i\)</span> (o piensa en <span class="math inline">\(\bar{v}\)</span> como el promedio de <span class="math inline">\(v_i\)</span>, aunque no es exactamente eso). Observa que el denominador es la varianza total que existe en los datos. Los valores de referencia para <span class="math inline">\(I^2\)</span> son 25, 50 y 75% para heterogeneidad baja, moderada y alta, respectivamente (Higgins <em>et al.</em> 2003).</p>
<p>Nuestro valor de <span class="math inline">\(I^2\)</span> es del 88.9%, muy alto, y este valor es, como esperabas, estadísticamente significativo al ser probado con el valor <span class="math inline">\(Q\)</span> (que sigue una distribución <span class="math inline">\(\chi^2\)</span> definida por el valor df, en este caso <span class="math inline">\(df = 101\)</span>).</p>
<p>Recientemente, hicimos un metaanálisis de metaanálisis (un metaanálisis secundario) para analizar cuál es el valor promedio de <span class="math inline">\(I^2\)</span> en el campo de la ecología y la evolución (Senior <em>et al.</em> 2016). ¡El valor promedio fue del 92%! Por lo tanto, esto indica que realmente deberíamos ajustar el modelo de efectos aleatorios en lugar del modelo de efecto común, ya que este último asume que la heterogeneidad es cero o <span class="math inline">\(\tau^2=0\)</span> e <span class="math inline">\(I^2 = 0\)</span>. ¿O realmente es así? Lo descubriremos más adelante.</p>
</section>
<section id="meta-regresión-el-modelo-de-efectos-aleatorios" class="level3">
<h3 class="anchored" data-anchor-id="meta-regresión-el-modelo-de-efectos-aleatorios">Meta-regresión (el modelo de efectos aleatorios)</h3>
<p>La existencia de heterogeneidad establece el escenario para la meta-regresión. Esto significa que ahora introducimos predictores (llamados ‘moderadores’ en la terminología metaanalítica) en nuestro modelo para explicar la heterogeneidad (equivalente a los modelos de regresión normales).</p>
<p>Ajustar una meta-regresión también es bastante sencillo. En este ejemplo, ajustaremos tres moderadores que fueron recopilados por los autores: 1) <code>time</code> (cuánto tiempo duró el experimento), 2) <code>method</code> (diferentes formas de aumentar el CO<span class="math inline">\(_2\)</span>) y 3) <code>fungroup</code> (grupo funcional, es decir, angiospermas, gimnospermas o fijadores de N<span class="math inline">\(_2\)</span>).</p>
<p>Utilizamos nuevamente <code>rma</code>, pero ahora con una declaración de modelo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>metareg <span class="ot">&lt;-</span> <span class="fu">rma</span>(<span class="at">yi =</span> yi, <span class="at">vi =</span> vi, <span class="at">mod =</span> <span class="sc">~</span>time <span class="sc">+</span> method <span class="sc">+</span> fungrp, <span class="at">method =</span> <span class="st">"REML"</span>,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data =</span> dat)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(metareg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Mixed-Effects Model (k = 102; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
  5.1938  -10.3876    3.6124   21.5628    4.8851   

tau^2 (estimated amount of residual heterogeneity):     0.0267 (SE = 0.0056)
tau (square root of estimated tau^2 value):             0.1634
I^2 (residual heterogeneity / unaccounted variability): 87.16%
H^2 (unaccounted variability / sampling variability):   7.79
R^2 (amount of heterogeneity accounted for):            0.00%

Test for Residual Heterogeneity:
QE(df = 96) = 658.4083, p-val &lt; .0001

Test of Moderators (coefficients 2:6):
QM(df = 5) = 2.9089, p-val = 0.7140

Model Results:

             estimate      se     zval    pval    ci.lb   ci.ub      
intrcpt        0.3043  0.0516   5.8934  &lt;.0001   0.2031  0.4055  *** 
time          -0.0001  0.0001  -1.0509  0.2933  -0.0002  0.0001      
methodGH      -0.0369  0.0567  -0.6501  0.5157  -0.1481  0.0743      
methodOTC      0.0308  0.0902   0.3410  0.7331  -0.1461  0.2076      
fungrpGYMNO   -0.0454  0.0605  -0.7501  0.4532  -0.1640  0.0732      
fungrpN2FIX    0.0044  0.1701   0.0258  0.9794  -0.3291  0.3379      

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Bueno, ¡no explican nada! Observa el valor <span class="math inline">\(R^2\)</span> y, como esperabas, las pruebas para moderadores (nuevamente el valor Q) indican que no son significativos. ¡Un modelo terrible! Así que nos damos por vencidos aquí (en un metaanálisis real, necesitas hacer esto de manera más sistemática, preferiblemente basado en tus hipótesis a priori).</p>
</section>
<section id="comprobando-el-sesgo-de-publicación" class="level3">
<h3 class="anchored" data-anchor-id="comprobando-el-sesgo-de-publicación">Comprobando el sesgo de publicación</h3>
<p>Bien, parece que un aumento de CO<span class="math inline">\(_2\)</span> promueve el crecimiento de las plantas (lo cual puede no ser sorprendente), pero estamos asumiendo que el conjunto de datos que tenemos no sufre de sesgo de publicación.</p>
<blockquote class="blockquote">
<p>El sesgo de publicación, en su forma más simple, significa que los resultados significativos son más propensos a ser publicados que los resultados no significativos.</p>
</blockquote>
<p>Pero existen varios métodos que las personas han estado utilizando. Los dos métodos más comunes, a menudo utilizados en conjunto, son: 1) gráfico de embudo (funnel plot), que se utiliza para detectar una asimetría en el embudo (un indicio de sesgo de publicación), y 2) la prueba de regresión de Egger, con la cual se prueba estadísticamente la asimetría del embudo.</p>
<p>¿A qué me refiero con ‘asimetría del embudo’? Si trazamos los tamaños de efecto y su error estándar en orden descendente (<span class="math inline">\(se\)</span>; ver figura a continuación), se supone que veremos un embudo invertido donde los tamaños de efecto con un <span class="math inline">\(se\)</span> bajo (o pesos altos) están más estrechamente agrupados que los tamaños de efecto con un <span class="math inline">\(se\)</span> alto (o pesos bajos). Pero esta forma de embudo solo ocurre cuando no hay sesgo de publicación. Si existe, deberíamos ver una asimetría en el embudo. Esto se debe a que los estudios con tamaños de muestra pequeños (es decir, <span class="math inline">\(se\)</span> alto, lo que conduce a no significancia) tienen menos probabilidades de ser publicados. Veremos un ejemplo de esta asimetría del embudo en nuestro conjunto de datos.</p>
<p>Para crear un gráfico de embudo y ejecutar la prueba de Egger:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">funnel</span>(random_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/funnel-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that the orignal Egger's test is regtest(random_m, model='lm')</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">regtest</span>(random_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression Test for Funnel Plot Asymmetry

Model:     mixed-effects meta-regression model
Predictor: standard error

Test for Funnel Plot Asymmetry: z = 3.2046, p = 0.0014
Limit Estimate (as sei -&gt; 0):   b = 0.1584 (CI: 0.0890, 0.2278)</code></pre>
</div>
</div>
<p>El gráfico de embudo y la prueba de Egger sugieren asimetría en el embudo. Pero debemos tener cuidado. La asimetría del embudo no solo puede ser causada por sesgo de publicación, sino también por heterogeneidad (uno o más moderadores no detectados que distorsionan la forma del embudo). Dado que tenemos mucha varianza inexplicada (es decir, heterogeneidad), no estamos seguros de qué está causando esta asimetría. Pero tenemos algunas evidencias de sesgo de publicación. Un punto relevante es que si la metarregresión explica mucha heterogeneidad, debes usar ese modelo de metarregresión en la función <code>regrest</code> (en nuestro caso, <code>regrest(metareg)</code>, pero no lo hice porque nuestro modelo <code>metareg</code> no explicaba nada).</p>
<p>Existe un método alternativo, que tiene un nombre interesante, el método de recorte y relleno (trim-and-fill). Verás la razón por la que se llama así. Podemos utilizar este método utilizando la función <code>trimfill</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Note that we are using the defult estimator ('L0'), but there are two others</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># availablere</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>tf_m <span class="ot">&lt;-</span> <span class="fu">trimfill</span>(random_m)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>tf_m</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Estimated number of missing studies on the left side: 13 (SE = 6.5629)

Random-Effects Model (k = 115; tau^2 estimator: REML)

tau^2 (estimated amount of total heterogeneity): 0.0421 (SE = 0.0076)
tau (square root of estimated tau^2 value):      0.2053
I^2 (total heterogeneity / total variability):   92.06%
H^2 (total variability / sampling variability):  12.59

Test for Heterogeneity:
Q(df = 114) = 872.7669, p-val &lt; .0001

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub      
  0.2166  0.0227  9.5234  &lt;.0001  0.1721  0.2612  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">funnel</span>(tf_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/trimfill-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Como puedes ver, este método utiliza la asimetría para agregar más puntos y proporcionar una media general revisada, que es menor que la del modelo de efectos aleatorios original. Aunque este efecto sigue siendo significativo, este método podría convertir una media general significativa en una no significativa. Pero en lugar de considerar esto como una estimación real de la media general, debemos verlo como parte de un análisis de sensibilidad.</p>
<p>Existen más métodos para realizar pruebas de sesgo de publicación, ninguno de los cuales es perfecto, pero debemos realizar algunas de estas pruebas (ver más en Nakagawa <em>et al.</em> 2017 y las referencias allí citadas).</p>
</section>
<section id="otro-modelo-que-no-conocía-pero-importante" class="level3">
<h3 class="anchored" data-anchor-id="otro-modelo-que-no-conocía-pero-importante">Otro modelo (que no conocía), ¡pero importante!</h3>
<p>Recientemente aprendí que existe otro modelo meta-analítico (ni común ni aleatorio) que es más robusto frente al sesgo de publicación. Recuerda lo que mencioné anteriormente.</p>
<ol type="1">
<li>El modelo de efectos aleatorios es un modelo más realista, por lo que deberíamos usar este modelo.</li>
<li>El modelo de efectos aleatorios tiene un peso de <span class="math inline">\(1/(\tau^2+v_i)\)</span>.</li>
<li><span class="math inline">\(I^2\)</span> es muy grande en conjuntos de datos meta-ecológicos y meta-evolutivos, lo que significa que <span class="math inline">\(\tau^2\)</span> es muy grande, lo que implica que <span class="math inline">\(1/(\tau^2+v_i) \approx 1/\tau^2\)</span> ya que <span class="math inline">\(v_i\)</span> es insignificante.</li>
<li>Entonces, todos los puntos de datos tienen el mismo peso <span class="math inline">\(1/\tau^2\)</span>, ¡y básicamente se convierte en un modelo no ponderado!</li>
</ol>
<p>Esto es problemático porque bajo el sesgo de publicación, como vimos anteriormente, los tamaños de efecto con tamaños de muestra pequeños (valores de <span class="math inline">\(v_i\)</span> muy altos) deberían tener un peso menor en comparación con los tamaños de efecto con tamaños de muestra grandes (valores de <span class="math inline">\(v_i\)</span> bajos). Cuando existe sesgo de publicación, el modelo de efectos aleatorios podría proporcionarnos una estimación sesgada… ¿Qué podríamos hacer? ¿Podríamos usar el peso de <span class="math inline">\(1/v_i\)</span> como en el modelo común, pero utilizar la estructura del modelo de efectos aleatorios? ¡Resulta que sí se puede!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We make weights, which is 1/vi and stick that into the argument, weights</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>dat[, <span class="st">"wi"</span>] <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">/</span>dat<span class="sc">$</span>vi</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>weight_m <span class="ot">&lt;-</span> <span class="fu">rma</span>(<span class="at">yi =</span> yi, <span class="at">vi =</span> vi, <span class="at">weights =</span> wi, <span class="at">method =</span> <span class="st">"REML"</span>, <span class="at">data =</span> dat)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(weight_m)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Random-Effects Model (k = 102; tau^2 estimator: REML)

  logLik  deviance       AIC       BIC      AICc   
  4.2927   -8.5854   -4.5854    0.6448   -4.4630   

tau^2 (estimated amount of total heterogeneity): 0.0262 (SE = 0.0053)
tau (square root of estimated tau^2 value):      0.1619
I^2 (total heterogeneity / total variability):   88.90%
H^2 (total variability / sampling variability):  9.01

Test for Heterogeneity:
Q(df = 101) = 769.0185, p-val &lt; .0001

Model Results:

estimate      se    zval    pval   ci.lb   ci.ub      
  0.2088  0.0473  4.4121  &lt;.0001  0.1161  0.3016  *** 

---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>En realidad, este estimador puntual es exactamente el mismo que el del modelo de efecto común (esto no es solo una coincidencia, ya que este modelo calcula la media general como el modelo de efecto común). Pero es importante tener en cuenta que este modelo tiene un intervalo de confianza del 97% más amplio que el modelo de efecto común, y este nivel de incertidumbre es más realista (al igual que el modelo de efectos aleatorios). Básicamente, ¡este modelo tiene lo mejor de ambos mundos!</p>
<p>Este modelo se basa en el artículo de Henmi y Copas (2010). Aunque es más robusto al sesgo de publicación, no conozco ningún metanálisis en el campo de la ecología y la evolución que utilice este modelo. ¿Probablemente deberíamos usar este modelo en lugar de un modelo de efectos aleatorios? Creo que sí, llamemos a este modelo el ‘modelo robusto’. Creo que también deberíamos usar este modelo robusto para la meta-regresión. Agradezco a Wolfgang por hablarme de este modelo.</p>
<p>Si estás de acuerdo con todo esto, pasa a los <a href="../../../statistics/meta-analysis/meta-analysis-3">modelos más complejos</a>.</p>
</section>
<section id="más-ayuda-referencias" class="level3">
<h3 class="anchored" data-anchor-id="más-ayuda-referencias">Más ayuda (referencias)</h3>
<p>¿Alguna pregunta? Envíame un correo electrónico a s(-dot-)nakagawa(-at-)unsw(-dot-)edu(-dot-)au. También visita nuestro <a href="http://www.i-deel.org/">sitio web</a>.</p>
<p>Visita el <a href="http://www.metafor-project.org/doku.php">sitio web</a> del paquete ‘metafor’. Allí encontrarás muchos ejemplos prácticos.</p>
<p style="margin-left:.5in;text-indent:-.5in">
Henmi, M., and J. B. Copas. 2010. Confidence intervals for random effects meta-analysis and robustness to publication bias. <em>Statistics in Medicine</em> 29:2969-2983.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
Higgins, J. P. T., S. G. Thompson, J. J. Deeks, and D. G. Altman. 2003. Measuring inconsistency in meta-analyses. <em>British Medical Journal</em> 327:557-560.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
Nakagawa, S., D. W. A. Noble, A. M. Senior, and M. Lagisz. 2017. Meta-evaluation of meta-analysis: ten appraisal questions for biologists. <em>BMC Biology</em> 15:18.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
Senior, A. M., C. E. Grueber, T. Kamiya, M. Lagisz, K. O’Dwyer, E. S. A. Santos, and S. Nakagawa. 2016. Heterogeneity in ecological and evolutionary meta-analyses: its magnitude and implications. <em>Ecology</em> 97:3293-3299.
</p>
<p><strong>Autores</strong>: Shinichi Nakagawa y Malgorzata (Losia) Lagisz</p>
<p><strong>Año</strong>: 2016</p>
<p><strong>Última actualización</strong>: Nov.&nbsp;2023</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../../statistics/meta-analysis/meta-analysis-1/index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Introduction al meta-análisis</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../../statistics/meta-analysis/meta-analysis-3/index.html" class="pagination-link">
        <span class="nav-page-text">Multilevel Models</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Environmental Computing - Spanish | Made with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>