---
weight: 2
title: "Two Sample T-test"
output: html_document
aliases: /independent-samples-t-test/
---



<p><em>t-test</em> de muestras independientes, también conocido como un <em>t-test</em> de dos muestras, es una de las pruebas estadísticas más comúnmente utilizadas. Se utiliza para comparar si las medias de dos muestras son estadísticamente diferentes entre sí (por ejemplo, control vs. tratamiento, sitio A vs. sitio B, etc.). Por ejemplo, consideremos el caso simple de si una muestra de mediciones de pH de un río difiere de una muestra de mediciones de pH de un segundo río.</p>
<p><img src="Independent_samples_t_test_image.jpg" /></p>
<p>La hipótesis nula es que las medias de la población de las cuales se toman las dos muestras son iguales <span class="math display">\[H_o: \mu_1=\mu_2\]</span>.</p>
<p>La estadística de prueba, <em>t</em>, es:</p>
<p><span class="math display">\[t = \frac{\bar{x_{1}}-\bar{x_{2}}}{s_{\bar{y_{1}}-\bar{y_{2}}}}\]</span></p>
<p>donde el denominador es el error estándar de la diferencia entre las dos medias.</p>
<p><span class="math display">\[\sqrt{\frac{(n_{1}-1)s_{1}^{2}+(n_{2}-1)s_{2}^{2}}{n_{1}+n_{2}-2}{(\frac{1}{n_{1}}}+\frac{1}{n_{2}})}\]</span></p>
<p>Ten en cuenta que el tamaño de la estadística de prueba depende de dos cosas: 1) qué tan diferentes son las dos medias (el numerador) y 2) cuánta variación hay presente dentro de cada muestra (el denominador).</p>
<p>Esta ecuación es para el <em>t</em>-test de varianza combinada. Para un <em>t</em>-test de varianzas separadas (también conocido como <em>t</em>-test de Welch), que no asume varianzas iguales, el denominador es:</p>
<p><span class="math display">\[\sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}}\]</span></p>
<p>Ten en cuenta que un <em>t</em>-test es un caso especial de un modelo lineal con una variable de respuesta continua única y un predictor categórico único que tiene dos niveles.</p>
<div id="ejecución-del-análisis" class="section level3">
<h3>Ejecución del análisis</h3>
<p>Un <em>t</em>-test de muestras independientes se puede ejecutar con la misma función <code>t.test</code> utilizada para <a href="/statistics/t-tests/one-sample-t-test/">una muestra</a> o <a href="/statistics/t-tests/paired-t-test/">t*-tests pareados</a>. Para un <em>t</em>-test de muestras independientes que asume varianzas iguales, usaríamos:</p>
<pre class="r"><code>t.test(x &lt;- my_sample1, y = my_sample2, var.equal = TRUE)</code></pre>
<p>Donde <em>my_sample1</em> y <em>my_sample2</em> son vectores que contienen las mediciones de cada muestra.</p>
<p>Más comúnmente, usaríamos un data frame con las variables de respuesta y predictor como columnas separadas. Luego puedes usar una declaración de fórmula, <code>y ~ x</code>, para especificar las variables de respuesta y predictor en lugar del código anterior. Considera el ejemplo simple en el que deseas comparar el pH de dos ríos. Se tomaron diez medidas replicadas de pH de cada río.</p>
<p>Descarga el conjunto de datos de muestra, <a href="/datasets/River_pH.csv">River_pH.csv</a>, e impórtalo en R.</p>
<pre class="r"><code>River_pH &lt;- read.csv(file = &quot;River_pH.csv&quot;, header = TRUE)</code></pre>
<p>El test <em>t</em> se realiza con la función <code>t.test</code>, donde los argumentos especifican la variable de respuesta (pH) a la izquierda de ~, la variable predictora (River_name) a la derecha de ~, y el marco de datos a utilizar.</p>
<pre class="r"><code>t.test(pH ~ River_name, data = River_pH, var.equal = TRUE)</code></pre>
<p>El argumento <code>var.equal = TRUE</code> especifica que asumimos varianzas iguales. Ten en cuenta que el argumento predeterminado del test <code>t</code> para la hipótesis alternativa es una prueba bilateral. Si deseas realizar una prueba unilateral, debes agregar un argumento a la función que especifique <code>alternative = "greater"</code> o <code>alternative = "less"</code>.</p>
</div>
<div id="interpretación-de-los-resultados" class="section level3">
<h3>Interpretación de los resultados</h3>
<pre><code>## 
## 	Two Sample t-test
## 
## data:  River_pH$pH by River_pH$River_name
## t = 6.9788, df = 18, p-value = 1.618e-06
## alternative hypothesis: true difference in means between group A and group B is not equal to 0
## 95 percent confidence interval:
##  1.574706 2.931168
## sample estimates:
## mean in group A mean in group B 
##        8.661497        6.408560</code></pre>
<p>La salida de un test <em>t</em> es fácil de interpretar. En la salida anterior, el estadístico de prueba <em>t</em> = 6.9788 con 18 grados de libertad, y un valor de <em>p</em> muy bajo (<em>p</em> &lt; 0.001). Por lo tanto, podemos rechazar la hipótesis nula de que los dos ríos tienen el mismo pH.</p>
<p>También se obtienen las medias de las dos muestras (necesario para saber cuál es mayor si el test es significativo) y el intervalo de confianza del 95% para la diferencia entre las dos medias (este no se superpondrá con cero cuando el test sea significativo).</p>
</div>
<div id="supuestos-a-verificar" class="section level3">
<h3>Supuestos a verificar</h3>
<p>Los tests <em>t</em> son tests paramétricos, lo que implica que podemos especificar una distribución de probabilidad para la población de la variable de la cual se tomaron las muestras. Los tests paramétricos (y no paramétricos) tienen varios supuestos. Si se violan estos supuestos, ya no podemos estar seguros de que el estadístico de prueba siga una distribución <em>t</em>, y en ese caso, los valores de <em>p</em> pueden ser inexactos.</p>
<p><strong>Normalidad</strong>. Los datos siguen una distribución normal. Sin embargo, los tests <em>t</em> son razonablemente robustos frente a violaciones de la normalidad (aunque hay que tener cuidado con la influencia de los valores atípicos).</p>
<p><strong>Varianza igual</strong>. Se asume que las varianzas de cada muestra son aproximadamente iguales. Los tests <em>t</em> también son razonablemente robustos frente a violaciones de la igualdad de varianzas si los tamaños de las muestras son iguales, pero pueden ser problemáticos cuando los tamaños de las muestras son muy diferentes.</p>
<p>En caso de varianzas desiguales, puede ser mejor realizar un test <em>t</em> de Welch, que no asume igualdad de varianzas. Para realizar un test de Welch en R, el argumento <code>var.equal</code> en la función <code>t.test</code> debe cambiarse a <code>var.equal=FALSE</code>. De hecho, este es el argumento predeterminado para <code>t.test</code> si no se especifica.</p>
<p><strong>Independencia</strong>. Las observaciones deben haber sido muestreadas aleatoriamente de la población, de manera que las medias de las dos muestras sean estimaciones no sesgadas de las medias de la población. Si los individuos replicados están vinculados de alguna manera, se violará el supuesto de independencia.</p>
</div>
<div id="comunicación-de-los-resultados" class="section level3">
<h3>Comunicación de los resultados</h3>
<p><strong>Escrita</strong>. Como mínimo, se debe informar el estadístico de prueba <em>t</em> observado, el valor de <em>p</em> y el número de grados de libertad. Por ejemplo, podrías escribir “el pH fue significativamente más alto en el Río A que en el Río B (test de muestras independientes <em>t</em>: <em>t</em> = 6.98, df = 18, P &lt; 0.001)”.</p>
<p><strong>Visual</strong>. Los diagramas de caja o los gráficos de columnas con barras de error son formas efectivas de comunicar la variación en una única variable de respuesta continua en comparación con una única variable predictora categórica.</p>
<pre class="r"><code>boxplot(pH ~ River_name, data = River_pH, xlab = &quot;River name&quot;, ylab = &quot;pH&quot;)</code></pre>
<p><img src="/Statistics/t-tests/two-sample-t-test/_index_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="más-ayuda" class="section level3">
<h3>Más ayuda</h3>
<p>Escribe <code>?t.test</code> para obtener la ayuda de R sobre esta función.</p>
<p style="margin-left:.5in;text-indent:-.5in">
Quinn y Keough (2002) <em>Experimental design and data analysis for biologists.</em> Cambridge University Press. Capítulo 3: Prueba de hipótesis.
</p>
<p style="margin-left:.5in;text-indent:-.5in">
McKillup (2012) <em>Statistics explained. An introductory guide for life scientists.</em> Cambridge University Press. Capítulo 9: Comparación de las medias de una y dos muestras de datos distribuidos normalmente.
</p>
<p><strong>Autor</strong>: Alistair Poore</p>
<p><strong>Año</strong>: 2016</p>
<p><strong>Última actualización</strong>: Jun. 2023</p>
</div>
